### ISSUE TITLE
Logging of the `current_wrapper_name` no longer shows up in Rails 6.1

### ISSUE THREAD

**Issue by ridiculous** [ankane/distribute_reads#55]
It used to log `[primary] User Load` now it just shows `User Load`.

**Comment by ankane** [comment]
Hi @ridiculous, looks like it's due to https://github.com/rails/rails/pull/38013. `current_wrapper_name` is in Makara, so you'll want to report it there. [Here's a fix](https://github.com/ankane/makara/commit/3469dcc7a11b2a77fe235cc8754051b0b1e0dae6), but it'll probably need a test case to be accepted (if someone wants to run with it).

**Comment by ridiculous** [comment]
Thanks. Yeah I was also thinking we could use the payload connection

**Comment by ridiculous** [comment]
Sorry I was looking in that subscriber class and totally missed its in the makara lib. Lol sorry to bug you

**Comment by ankane** [comment]
Ha, no worries
